### ISSUE TITLE
Critical Bug - Continue UI re-render

### ISSUE THREAD

**Issue by nidhish-nayak** [NeoFoxxo/plottwist#61]
## Bug - UI does not re-render to show updated story response

- Continue response sends the correct data, database is updated correctly.
- All the features work. Only problem is the new story response from ContinueStory is not rendered on UI with updated data.
- This somehow works for "choices" and it re-renders correctly.
- You can check the response & database to see that new story is correctly retrieved.
- Hence it is most probably the UI re-render issue.

## For now user has to refresh page to see updates to story.

Files in Use and to look into:
![image](https://github.com/NeoFoxxo/plottwist/assets/76598208/2d8e1cc4-c149-49f8-8e90-2c2d882ce99c)

**Comment by NeoFoxxo** [comment]
will fix this tonight
